# This file is part of Friends and Family CA.
#
# Copyright (C) 2026 Marko Ivankovic
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# The enrollment page's image as a release publishes it: the static binary the release built for
# the image's architecture, on an empty base, run as nobody. The build context is a folder holding
# `ffca-amd64/ffca` and `ffca-arm64/ffca` - see .github/workflows/release.yml. To build from source
# instead, use the Dockerfile beside this one.
FROM scratch
ARG TARGETARCH
COPY --chmod=0755 ffca-${TARGETARCH}/ffca /ffca
USER 65534:65534
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=5s CMD ["/ffca", "healthz"]
ENTRYPOINT ["/ffca"]
CMD ["serve", "--listen", "0.0.0.0:8080", "--invites", "/invites"]
